### ISSUE TITLE
replay piepje werkt niet

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-lexical-decision#15]
Als ik op 'play again' klik bij het piepje aan het begin, gaat het exp door, en speelt niet opnieuw het piepje af.

**Comment by maartenuni** [comment]
Ik ga er naar kijken.

**Comment by maartenuni** [comment]
Ik denk dat we in het verleden een keertje jsPsych voor dit experiment hebben geupgradet. Daardoor zaten er andere attributen op een variablele, nu werd de verkeerde gebruikt en werd 0 met None vergeleken ipv een geldig nummer, daardoor werd ongeacht welke knop je drukte door gegaan naar het volgende stuk van de tijdlijn.
Dit probleem is nu opgelost.
